name: Deploy to server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest     
      
    steps:
      
      - name: Deploy app 
        uses:  appleboy/ssh-action@master
        env: 
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_NAME: ${{ secrets.PG_NAME }}
          
        with:
          envs: PG_USER,PG_PASSWORD,PG_NAME
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf RBS/ && git clone https://github.com/jacobnocoffeeee/RBS.git
            cd RBS/mini_app && ./deploy.sh
